#!/usr/bin/env python                                                                                                                                                                                                                 
#                                                                                                                                                                                                                                      
# See top-level LICENSE.rst file for Copyright information                                                                                                                                                                            
#                                                                                                                                                                                                                                     
# -*- coding: utf-8 -*- 

#  ----  Calling  ----
#- salloc -N 6 -C haswell -q interactive -t 02:00:00
#-   srun -N 6 -n 24 -c 4 python mpi_radlss
#-   srun -N 6 -n 32 -c 2 python mpi_radlss (spectra & redrock).
#-
#-   24 mins. per exposure (all ten petals, brz).
#-   45 exposures to process for 20200315.
#-
import multiprocessing

from   mpi4py                    import  MPI

nproc = multiprocessing.cpu_count() // 2

comm  = MPI.COMM_WORLD
rank  = comm.Get_rank()
size  = comm.Get_size()

# -----------------------------------------------------------
import os
import sys
import time
import glob
import fitsio

import itertools
import warnings

import numpy as np
import pylab as pl

import desispec.io
import desisim.templates
import astropy.io.fits           as      fits
import matplotlib.pyplot         as      plt

from   os                        import  path
from   astropy.table             import  Table
from   pathlib                   import  Path
from   RadLSS                    import  RadLSS
from   desispec.parallel         import  stdouterr_redirected


prod = '/global/cfs/cdirs/desi/spectro/redux/blanc/'
odir = '/global/cscratch1/sd/mjwilson/radlss/blanc/'

def get_expids(night, prod=prod):
    '''
    Get the exposure list for a given night of the specified reduction. 
    '''
    tiles  = np.unique(np.array([x.split('/')[-3] for x in glob.glob(prod + '/tiles/*/{}/cframe-*'.format(night))]).astype(np.int))

    # np.sort(np.array([x.split('/')[-1] for x in glob.glob(prod + '/exposures/{}/*'.format(night))]).astype(np.int))  
    expids = np.unique(np.array([x.split('/')[-1].split('-')[2].replace('.fits','') for x in glob.glob(prod + '/tiles/*/{}/cframe-*'.format(night))]).astype(np.int)) 
    
    return  expids, tiles
    
def is_processed(logfile):
    '''
    Query whether this epxosure has been reduced already (SUCCESS present in written logfile.)
    '''
    processed     = False

    if path.exists(logfile):
        f           = open(logfile)
        
        if 'SUCCESS' in f.read():
            processed = True

        f.close()
    
    return  processed

# Night to reduce.
night     = '20201223'

# Tracers to sample fiber variance. 
tracers   = ['BGS']

#
overwrite = True

# ------------------------------ #
expids, tiles = get_expids(night)

# Test set. 
expids    = [69611]

# One petal test set, e.g. ['b6', 'r6', 'z6'] or full: cameras=None.  
cameras   = ['b6', 'r6', 'z6']
# cameras = None

comm.barrier()

expids    = comm.bcast(expids, root=0)

if rank == 0:
    print('Number of exposures to process: {}'.format(len(expids)))

# Divide exposures amongst available ranks. 
#     See https://github.com/desihub/desitarget/blob/master/bin/mpi_select_mock_targets
iexp      = np.linspace(0, len(expids), size+1, dtype=int)
rankexp   = expids[iexp[rank]:iexp[rank+1]]

print('rank {} processes {} exposures {}'.format(rank, iexp[rank+1]-iexp[rank], rankexp))

sys.stdout.flush()

comm.barrier()

if len(rankexp) > 0:    
    for nexp, expid in enumerate(rankexp):        
        start    = time.perf_counter()
      
        logdir   = odir + '/logs/{:08d}/'.format(expid)
        logfile  = logdir + '/{:08d}.log'.format(expid) 

        if overwrite:
            done = 0
            
        else:
            done = is_processed(logfile)
        
        if not done:      
            Path(logdir).mkdir(parents=True, exist_ok=True)

            print('Rank {}:  Writing log for {:08d} to {}.'.format(rank, expid, logfile))

            with stdouterr_redirected(to=logfile):
                print('Rank {}: Solving for EXPID {:08d} ({} of {})'.format(rank, expid, nexp, len(rankexp)))
        
                rads = RadLSS(night, expid, cameras=cameras, rank=rank, shallow=False, outdir=odir)
                
                rads.compute(tracers=tracers)
                
                print('Rank {}:  SUCCESS.  Processed EXPID {:08d} in {:.3f} minutes.'.format(rank, expid, (time.perf_counter() - start) / 60.))
                
                # Close all figures (to suppress warning). 
                plt.close('all')
                              
                sys.stdout.flush()

            if rads.flavor != 'science':
                print('Rank {}:  {:08d}  Non-science exposure ({}).'.format(rank, expid, rads.flavor))
                    
            del rads
                
        else:
            print('Rank {}:  EXPID {} previously processed successfully.'.format(rank, expid))
